GETP-139 feature: 피플 정보 등록 페이지 구현
Principes-Artis-Mechanicae/get-p-frontend pull request #43
Opened 2024-06-30 08:19 UTC by chominju02

## ✨ 구현한 기능

- 피플 정보 등록 페이지 구현

## 📢 논의하고 싶은 내용

-

## 🎸 기타

-

2024-07-01 14:29 UTC, toothlessdev requested changes

2024-07-01 14:29 UTC, toothlessdev commented on src/pages/people/PeopleInfoRegisterPage.style.tsx
> +`;
버튼 너비 48% 로 두고 space-between 하지마시고
버튼너비 50% 로 주신 다음에 gap 속성 주시는게 더 좋을것 같습니다

2024-07-01 14:40 UTC, toothlessdev commented on src/pages/people/PeopleInfoRegisterPage.style.tsx
> +`;
페이지 구현하고 `App.tsx` 에 라우트 연결해주면 좋을것 같아요

2024-07-03 10:38 UTC, chominju02 commented on src/pages/people/PeopleInfoRegisterPage.style.tsx
> +`;
수정했습니다!

2024-07-03 10:39 UTC, toothlessdev approved these changes
LGTM

2024-07-03 10:39 UTC, merged