GETP-146 feature: 피플 상세 조회 페이지 퍼블리싱
Principes-Artis-Mechanicae/get-p-frontend pull request #46
Opened 2024-06-30 18:19 UTC by chae-won-shin

## ✨ 구현한 기능

- 피플 상세 조회 퍼블리싱

## 📢 논의하고 싶은 내용

1.  정보 조회 페이지라 이 부분이 편집 불가능한 텍스트박스여야 할 것 같아서 input 컴포넌트를 사용하지 못했습니다. 그래서 새로 만들었는데 앞으로 비슷한 정보 조회 페이지 만들 때마다 계속 쓰일 것 같아서 따로 공통컴포넌트로 빼고 싶은데 어느 폴더에 넣어야 할지 모르겠어서... 일단 peopleDetailPage.style.tsx에 넣음... 어디로 옮기면 좋을까요
![image](https://github.com/Principes-Artis-Mechanicae/get-p-frontend/assets/96687276/88f429b8-83cf-4d1e-b6af-2736b0e60a7b)

2. 비슷한 이유로 기술스택 뱃지도 옆에 X 버튼이 없어야 하는데 이건 재사용할 수 있을 것 같아서 TechstackBadge 컴포넌트를 살짝 수정했습니다. 혹시나 충돌날까봐 말해둠

3. 모바일 버전 이런 느낌 어떠신지(이건 디자인팀과도 같이 이야기해봐야할 것 같습니다!)
![image](https://github.com/Principes-Artis-Mechanicae/get-p-frontend/assets/96687276/1ce04d7c-2335-4468-bdea-0ab9983bf308)

4. useMediaQuery 쓸 때 
```
 const isMobile = useMediaQuery({
        query: {mobile},
    });
```
이렇게 breakpoint.ts에 있는 mobile 가져다 쓰고 싶어서 요래조래 해봤는데 안돼서 string으로 박았습니다... 방법 아는 사람

## 🎸 기타

-

2024-07-01 14:33 UTC, toothlessdev commented
1. 정보 조회 페이지라 이 부분이 편집 불가능한 텍스트박스여야 할 것 같아서 input 컴포넌트를 사용하지 못했습니다. 그래서 새로 만들었는데 앞으로 비슷한 정보 조회 페이지 만들 때마다 계속 쓰일 것 같아서 따로 공통컴포넌트로 빼고 싶은데 어느 폴더에 넣어야 할지 모르겠어서... 일단 peopleDetailPage.style.tsx에 넣음... 어디로 옮기면 좋을까요

> 기본적으로 html property 에 있는 disabled 속성을 사용하는것도 좋아보입니다

2. 비슷한 이유로 기술스택 뱃지도 옆에 X 버튼이 없어야 하는데 이건 재사용할 수 있을 것 같아서 TechstackBadge 컴포넌트를 살짝 수정했습니다. 혹시나 충돌날까봐 말해둠

> 확인했습니다!

3. 모바일 버전 이런 느낌 어떠신지(이건 디자인팀과도 같이 이야기해봐야할 것 같습니다!)

> 저는 태블릿일때 저렇게 레이아웃 구성하고 모바일일때 프로필과 해시태그 컨테이너를 column 방향으로 배치하도록 설정해두었어요 (#44)

4. useMediaQuery 쓸 때

`breakpoint.ts` 에 있는 해당 미디어 쿼리 다음과 같이 쓰면 됩니다

```ts
import {mobile} from "@/style/breakpoint.ts"

export const StyledComponent = styled.div`
    ${mobile} {
        // 모바일 스타일
    }
`;
```

2024-07-01 14:37 UTC, toothlessdev requested changes

2024-07-01 14:37 UTC, toothlessdev commented on package.json
최대한 외부 라이브러리 없이 css 미디어쿼리로도 충분히 반응형으로 구현할 수 있어요
외부패키지 사용하면 js 번들사이즈도 커지니까 최대한 사용안하는쪽으로 앞으로 구현해봐요

2024-07-01 14:37 UTC, toothlessdev commented on src/App.tsx
> +                                    <Route path="people/peopleDetail" element={<PeopleDetailPage />}></Route>
라우팅시에 REST API 규칙에 맞추면 좋을것 같아요
peopledetail 인데 people 마다 페이지가 구성되어야겠죠?
그러면 `/people/:id` 이런식으로 구성하는게 좋아보여요

2024-07-01 14:37 UTC, toothlessdev commented on src/components/people/TechStackBadge.story.ts
>  };
이부분도 입력을 받지 않는 input 에 대해서는 disabled 속성 사용하는게 좋아보입니다
디자인팀과 함께 얘기해보는게 좋을것 같아요

2024-07-03 15:43 UTC, chae-won-shin commented on src/components/people/TechStackBadge.story.ts
>  };
이 부분은 input창이 있는 게 아니라 
```
<Paragraph size="m" weight="bold">
                {text}
            </Paragraph>
            {isInput ? <TechStackBadgeCloseIcon src={closeIcon} onClick={handleBadgeClick} /> : null}
```
이렇게 isInput이 true인 경우 버튼이 뜨는 거라 disabled 속성을 어느 부분에 적용해야 할지 잘 모르겠습니다ㅜㅜ

2024-07-03 16:20 UTC, toothlessdev approved these changes

2024-07-03 16:20 UTC, toothlessdev commented on src/pages/people/PeopleDetailPage.tsx
> +`;
styled components 들은 `.style.tsx` 로 분리해주면 좋을것같아요

2024-07-03 16:21 UTC, toothlessdev commented
LGTM!

2024-07-03 16:24 UTC, merged